//
// File generated by /usr/bin/rootcint at Thu Sep 27 15:08:56 2018

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME RooBernsteinEffiDictionary
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "RooBernsteinEffiDictionary.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void RooBernsteinEffi_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_RooBernsteinEffi(void *p = 0);
   static void *newArray_RooBernsteinEffi(Long_t size, void *p);
   static void delete_RooBernsteinEffi(void *p);
   static void deleteArray_RooBernsteinEffi(void *p);
   static void destruct_RooBernsteinEffi(void *p);
   static void streamer_RooBernsteinEffi(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::RooBernsteinEffi*)
   {
      ::RooBernsteinEffi *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::RooBernsteinEffi >(0);
      static ::ROOT::TGenericClassInfo 
         instance("RooBernsteinEffi", ::RooBernsteinEffi::Class_Version(), "./RooBernsteinEffi.h", 20,
                  typeid(::RooBernsteinEffi), ::ROOT::DefineBehavior(ptr, ptr),
                  &::RooBernsteinEffi::Dictionary, isa_proxy, 0,
                  sizeof(::RooBernsteinEffi) );
      instance.SetNew(&new_RooBernsteinEffi);
      instance.SetNewArray(&newArray_RooBernsteinEffi);
      instance.SetDelete(&delete_RooBernsteinEffi);
      instance.SetDeleteArray(&deleteArray_RooBernsteinEffi);
      instance.SetDestructor(&destruct_RooBernsteinEffi);
      instance.SetStreamerFunc(&streamer_RooBernsteinEffi);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::RooBernsteinEffi*)
   {
      return GenerateInitInstanceLocal((::RooBernsteinEffi*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::RooBernsteinEffi*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr RooBernsteinEffi::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *RooBernsteinEffi::Class_Name()
{
   return "RooBernsteinEffi";
}

//______________________________________________________________________________
const char *RooBernsteinEffi::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::RooBernsteinEffi*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int RooBernsteinEffi::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::RooBernsteinEffi*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void RooBernsteinEffi::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::RooBernsteinEffi*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *RooBernsteinEffi::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::RooBernsteinEffi*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void RooBernsteinEffi::Streamer(TBuffer &R__b)
{
   // Stream an object of class RooBernsteinEffi.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      RooAbsReal::Streamer(R__b);
      _x.Streamer(R__b);
      _y.Streamer(R__b);
      _z.Streamer(R__b);
      _coefList.Streamer(R__b);
      R__b >> _maxDegree1;
      R__b >> _maxDegree2;
      R__b >> _maxDegree3;
      R__b.CheckByteCount(R__s, R__c, RooBernsteinEffi::IsA());
   } else {
      R__c = R__b.WriteVersion(RooBernsteinEffi::IsA(), kTRUE);
      RooAbsReal::Streamer(R__b);
      _x.Streamer(R__b);
      _y.Streamer(R__b);
      _z.Streamer(R__b);
      _coefList.Streamer(R__b);
      R__b << _maxDegree1;
      R__b << _maxDegree2;
      R__b << _maxDegree3;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void RooBernsteinEffi::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class RooBernsteinEffi.
      TClass *R__cl = ::RooBernsteinEffi::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_x", &_x);
      R__insp.InspectMember(_x, "_x.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_y", &_y);
      R__insp.InspectMember(_y, "_y.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_z", &_z);
      R__insp.InspectMember(_z, "_z.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_coefList", &_coefList);
      R__insp.InspectMember(_coefList, "_coefList.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_maxDegree1", &_maxDegree1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_maxDegree2", &_maxDegree2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_maxDegree3", &_maxDegree3);
      RooAbsReal::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_RooBernsteinEffi(void *p) {
      return  p ? new(p) ::RooBernsteinEffi : new ::RooBernsteinEffi;
   }
   static void *newArray_RooBernsteinEffi(Long_t nElements, void *p) {
      return p ? new(p) ::RooBernsteinEffi[nElements] : new ::RooBernsteinEffi[nElements];
   }
   // Wrapper around operator delete
   static void delete_RooBernsteinEffi(void *p) {
      delete ((::RooBernsteinEffi*)p);
   }
   static void deleteArray_RooBernsteinEffi(void *p) {
      delete [] ((::RooBernsteinEffi*)p);
   }
   static void destruct_RooBernsteinEffi(void *p) {
      typedef ::RooBernsteinEffi current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_RooBernsteinEffi(TBuffer &buf, void *obj) {
      ((::RooBernsteinEffi*)obj)->::RooBernsteinEffi::Streamer(buf);
   }
} // end of namespace ROOTDict for class ::RooBernsteinEffi

/********************************************************
* RooBernsteinEffiDictionary.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableRooBernsteinEffiDictionary();

extern "C" void G__set_cpp_environmentRooBernsteinEffiDictionary() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("RooBernsteinEffi.h");
  G__cpp_reset_tagtableRooBernsteinEffiDictionary();
}
#include <new>
extern "C" int G__cpp_dllrevRooBernsteinEffiDictionary() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* RooBernsteinEffi */
static int G__RooBernsteinEffiDictionary_774_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   RooBernsteinEffi* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new RooBernsteinEffi[n];
     } else {
       p = new((void*) gvp) RooBernsteinEffi[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new RooBernsteinEffi;
     } else {
       p = new((void*) gvp) RooBernsteinEffi;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_RooBernsteinEffi));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RooBernsteinEffiDictionary_774_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   RooBernsteinEffi* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 9
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new RooBernsteinEffi(
(const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])
, *(RooAbsReal*) libp->para[2].ref, *(RooAbsReal*) libp->para[3].ref
, *(RooAbsReal*) libp->para[4].ref, *(RooArgList*) libp->para[5].ref
, (int) G__int(libp->para[6]), (int) G__int(libp->para[7])
, (int) G__int(libp->para[8]));
   } else {
     p = new((void*) gvp) RooBernsteinEffi(
(const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])
, *(RooAbsReal*) libp->para[2].ref, *(RooAbsReal*) libp->para[3].ref
, *(RooAbsReal*) libp->para[4].ref, *(RooArgList*) libp->para[5].ref
, (int) G__int(libp->para[6]), (int) G__int(libp->para[7])
, (int) G__int(libp->para[8]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_RooBernsteinEffi));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RooBernsteinEffiDictionary_774_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   RooBernsteinEffi* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 2:
     //m: 2
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new RooBernsteinEffi(*(RooBernsteinEffi*) libp->para[0].ref, (const char*) G__int(libp->para[1]));
     } else {
       p = new((void*) gvp) RooBernsteinEffi(*(RooBernsteinEffi*) libp->para[0].ref, (const char*) G__int(libp->para[1]));
     }
     break;
   case 1:
     //m: 1
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new RooBernsteinEffi(*(RooBernsteinEffi*) libp->para[0].ref);
     } else {
       p = new((void*) gvp) RooBernsteinEffi(*(RooBernsteinEffi*) libp->para[0].ref);
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_RooBernsteinEffi));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RooBernsteinEffiDictionary_774_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const RooBernsteinEffi*) G__getstructoffset())->evaluateInt((fptype) G__double(libp->para[0]), (fptype) G__double(libp->para[1])
, (fptype) G__double(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RooBernsteinEffiDictionary_774_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) RooBernsteinEffi::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RooBernsteinEffiDictionary_774_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) RooBernsteinEffi::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RooBernsteinEffiDictionary_774_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) RooBernsteinEffi::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RooBernsteinEffiDictionary_774_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      RooBernsteinEffi::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RooBernsteinEffiDictionary_774_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((RooBernsteinEffi*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RooBernsteinEffiDictionary_774_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) RooBernsteinEffi::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RooBernsteinEffiDictionary_774_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) RooBernsteinEffi::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RooBernsteinEffiDictionary_774_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) RooBernsteinEffi::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RooBernsteinEffiDictionary_774_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) RooBernsteinEffi::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef RooBernsteinEffi G__TRooBernsteinEffi;
static int G__RooBernsteinEffiDictionary_774_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (RooBernsteinEffi*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((RooBernsteinEffi*) (soff+(sizeof(RooBernsteinEffi)*i)))->~G__TRooBernsteinEffi();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (RooBernsteinEffi*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((RooBernsteinEffi*) (soff))->~G__TRooBernsteinEffi();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* RooBernsteinEffi */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncRooBernsteinEffiDictionary {
 public:
  G__Sizep2memfuncRooBernsteinEffiDictionary(): p(&G__Sizep2memfuncRooBernsteinEffiDictionary::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncRooBernsteinEffiDictionary::*p)();
};

size_t G__get_sizep2memfuncRooBernsteinEffiDictionary()
{
  G__Sizep2memfuncRooBernsteinEffiDictionary a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceRooBernsteinEffiDictionary() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_RooBernsteinEffi))) {
     RooBernsteinEffi *G__Lderived;
     G__Lderived=(RooBernsteinEffi*)0x1000;
     {
       RooAbsReal *G__Lpbase=(RooAbsReal*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_RooBernsteinEffi),G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_RooAbsReal),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       RooAbsArg *G__Lpbase=(RooAbsArg*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_RooBernsteinEffi),G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_RooAbsArg),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TNamed *G__Lpbase=(TNamed*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_RooBernsteinEffi),G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_TNamed),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_RooBernsteinEffi),G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       RooPrintable *G__Lpbase=(RooPrintable*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_RooBernsteinEffi),G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_RooPrintable),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableRooBernsteinEffiDictionary() {

   /* Setting up typedef entry */
   G__search_typename2("Double_t",100,-1,0,-1);
   G__setnewtype(-1,"Double 8 bytes",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("set<std::string>",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_setlEstringcOlesslEstringgRcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("set<string>",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_setlEstringcOlesslEstringgRcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,std::string>",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,std::string>",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,string>",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,string,less<string> >",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("set<std::pair<RooAbsArg*,RooAbsArg*> >",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_setlEpairlERooAbsArgmUcORooAbsArgmUgRcOlesslEpairlERooAbsArgmUcORooAbsArgmUgRsPgRcOallocatorlEpairlERooAbsArgmUcORooAbsArgmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("set<pair<RooAbsArg*,RooAbsArg*> >",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_setlEpairlERooAbsArgmUcORooAbsArgmUgRcOlesslEpairlERooAbsArgmUcORooAbsArgmUgRsPgRcOallocatorlEpairlERooAbsArgmUcORooAbsArgmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("set<pair<RooAbsArg*,RooAbsArg*> >",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_setlEpairlERooAbsArgmUcORooAbsArgmUgRcOlesslEpairlERooAbsArgmUcORooAbsArgmUgRsPgRcOallocatorlEpairlERooAbsArgmUcORooAbsArgmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("set<pair<RooAbsArg*,RooAbsArg*>,less<pair<RooAbsArg*,RooAbsArg*> > >",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_setlEpairlERooAbsArgmUcORooAbsArgmUgRcOlesslEpairlERooAbsArgmUcORooAbsArgmUgRsPgRcOallocatorlEpairlERooAbsArgmUcORooAbsArgmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("deque<RooAbsCache*>",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_dequelERooAbsCachemUcOallocatorlERooAbsCachemUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<RooAbsArg*,TRefArray*>",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_maplERooAbsArgmUcOTRefArraymUcOlesslERooAbsArgmUgRcOallocatorlEpairlERooAbsArgmUsPconstcOTRefArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<RooAbsArg*,TRefArray*,less<RooAbsArg*> >",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_maplERooAbsArgmUcOTRefArraymUcOlesslERooAbsArgmUgRcOallocatorlEpairlERooAbsArgmUsPconstcOTRefArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("deque<RooAbsArg*>",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_dequelERooAbsArgmUcOallocatorlERooAbsArgmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("stack<RooAbsArg*>",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_stacklERooAbsArgmUcOdequelERooAbsArgmUcOallocatorlERooAbsArgmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Double_t>",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_TMatrixTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<RooCurve*>",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_vectorlERooCurvemUcOallocatorlERooCurvemUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_reverse_iteratorlEvectorlERooCurvemUcOallocatorlERooCurvemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_vectorlERooCurvemUcOallocatorlERooCurvemUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_reverse_iteratorlEvectorlERooCurvemUcOallocatorlERooCurvemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_vectorlERooCurvemUcOallocatorlERooCurvemUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("list<Double_t>",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_listlEdoublecOallocatorlEdoublegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TH1*>",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_maplEstringcOTH1mUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTH1mUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TH1*>",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_maplEstringcOTH1mUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTH1mUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TH1*>",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_maplEstringcOTH1mUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTH1mUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TH1*,less<string> >",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_maplEstringcOTH1mUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTH1mUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,RooDataHist*>",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_maplEstringcORooDataHistmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcORooDataHistmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,RooDataHist*>",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_maplEstringcORooDataHistmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcORooDataHistmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,RooDataHist*>",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_maplEstringcORooDataHistmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcORooDataHistmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,RooDataHist*,less<string> >",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_maplEstringcORooDataHistmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcORooDataHistmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,RooDataSet*>",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_maplEstringcORooDataSetmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcORooDataSetmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,RooDataSet*>",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_maplEstringcORooDataSetmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcORooDataSetmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,RooDataSet*>",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_maplEstringcORooDataSetmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcORooDataSetmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,RooDataSet*,less<string> >",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_maplEstringcORooDataSetmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcORooDataSetmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,RooAbsData*>",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_maplEstringcORooAbsDatamUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcORooAbsDatamUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,RooAbsData*>",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_maplEstringcORooAbsDatamUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcORooAbsDatamUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,RooAbsData*>",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_maplEstringcORooAbsDatamUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcORooAbsDatamUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,RooAbsData*,less<string> >",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_maplEstringcORooAbsDatamUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcORooAbsDatamUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("list<EvalError>",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_listlERooAbsRealcLcLEvalErrorcOallocatorlERooAbsRealcLcLEvalErrorgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("list<RooAbsReal::EvalError>",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_listlERooAbsRealcLcLEvalErrorcOallocatorlERooAbsRealcLcLEvalErrorgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<std::string,std::list<EvalError> >",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_pairlEstringcOlistlERooAbsRealcLcLEvalErrorcOallocatorlERooAbsRealcLcLEvalErrorgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<string,std::list<EvalError> >",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_pairlEstringcOlistlERooAbsRealcLcLEvalErrorcOallocatorlERooAbsRealcLcLEvalErrorgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<const RooAbsArg*,std::pair<std::string,std::list<EvalError> > >",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_maplEconstsPRooAbsArgmUcOpairlEstringcOlistlERooAbsRealcLcLEvalErrorcOallocatorlERooAbsRealcLcLEvalErrorgRsPgRsPgRcOlesslEconstsPRooAbsArgmUgRcOallocatorlEpairlEconstsPRooAbsArgmUsPconstcOpairlEstringcOlistlERooAbsRealcLcLEvalErrorcOallocatorlERooAbsRealcLcLEvalErrorgRsPgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<const RooAbsArg*,std::pair<string,std::list<EvalError> > >",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_maplEconstsPRooAbsArgmUcOpairlEstringcOlistlERooAbsRealcLcLEvalErrorcOallocatorlERooAbsRealcLcLEvalErrorgRsPgRsPgRcOlesslEconstsPRooAbsArgmUgRcOallocatorlEpairlEconstsPRooAbsArgmUsPconstcOpairlEstringcOlistlERooAbsRealcLcLEvalErrorcOallocatorlERooAbsRealcLcLEvalErrorgRsPgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<const RooAbsArg*,pair<string,list<RooAbsReal::EvalError,allocator<RooAbsReal::EvalError> > > >",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_maplEconstsPRooAbsArgmUcOpairlEstringcOlistlERooAbsRealcLcLEvalErrorcOallocatorlERooAbsRealcLcLEvalErrorgRsPgRsPgRcOlesslEconstsPRooAbsArgmUgRcOallocatorlEpairlEconstsPRooAbsArgmUsPconstcOpairlEstringcOlistlERooAbsRealcLcLEvalErrorcOallocatorlERooAbsRealcLcLEvalErrorgRsPgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<const RooAbsArg*,pair<string,list<RooAbsReal::EvalError,allocator<RooAbsReal::EvalError> > >,less<const RooAbsArg*> >",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_maplEconstsPRooAbsArgmUcOpairlEstringcOlistlERooAbsRealcLcLEvalErrorcOallocatorlERooAbsRealcLcLEvalErrorgRsPgRsPgRcOlesslEconstsPRooAbsArgmUgRcOallocatorlEpairlEconstsPRooAbsArgmUsPconstcOpairlEstringcOlistlERooAbsRealcLcLEvalErrorcOallocatorlERooAbsRealcLcLEvalErrorgRsPgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("list<std::string>",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_listlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("list<string>",117,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_listlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("fptype",100,-1,0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* RooBernsteinEffi */
static void G__setup_memvarRooBernsteinEffi(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_RooBernsteinEffi));
   { RooBernsteinEffi *p; p=(RooBernsteinEffi*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_RooRealProxy),-1,-1,2,"_x=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_RooRealProxy),-1,-1,2,"_y=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_RooRealProxy),-1,-1,2,"_z=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_RooListProxy),-1,-1,2,"_coefList=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,2,"_maxDegree1=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,2,"_maxDegree2=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,2,"_maxDegree3=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarRooBernsteinEffiDictionary() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncRooBernsteinEffi(void) {
   /* RooBernsteinEffi */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_RooBernsteinEffi));
   G__memfunc_setup("RooBernsteinEffi",1620,G__RooBernsteinEffiDictionary_774_0_1, 105, G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_RooBernsteinEffi), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("RooBernsteinEffi",1620,G__RooBernsteinEffiDictionary_774_0_2, 105, G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_RooBernsteinEffi), -1, 0, 9, 1, 1, 0, 
"C - - 10 - name C - - 10 - title "
"u 'RooAbsReal' - 1 - x u 'RooAbsReal' - 1 - y "
"u 'RooAbsReal' - 1 - z u 'RooArgList' - 11 - coefList "
"i - - 0 - maxDegree1 i - - 0 - maxDegree2 "
"i - - 0 - maxDegree3", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("RooBernsteinEffi",1620,G__RooBernsteinEffiDictionary_774_0_3, 105, G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_RooBernsteinEffi), -1, 0, 2, 1, 1, 0, 
"u 'RooBernsteinEffi' - 11 - other C - - 10 '0' name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("clone",529,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_TObject), -1, 0, 1, 1, 1, 8, "C - - 10 - newname", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("evaluateInt",1154,G__RooBernsteinEffiDictionary_774_0_5, 100, -1, G__defined_typename("Double_t"), 0, 3, 1, 1, 8, 
"d - 'fptype' 0 - xBinw d - 'fptype' 0 - yBinw "
"d - 'fptype' 0 - zBinw", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("evaluate",855,(G__InterfaceMethod) NULL, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 2, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("device_bernsteinkn_func",2429,(G__InterfaceMethod) NULL, 100, -1, G__defined_typename("fptype"), 0, 3, 1, 4, 8, 
"d - 'fptype' 0 - x d - 'fptype' 0 - enne "
"d - 'fptype' 0 - kappa", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("device_coeffbinomial",2077,(G__InterfaceMethod) NULL, 100, -1, G__defined_typename("fptype"), 0, 2, 1, 4, 8, 
"d - 'fptype' 0 - enne d - 'fptype' 0 - kappa", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("device_EffiBernsteinkn_intgBin",3062,(G__InterfaceMethod) NULL, 100, -1, G__defined_typename("fptype"), 0, 4, 1, 4, 8, 
"d - 'fptype' 0 - xLeft d - 'fptype' 0 - xRight "
"d - 'fptype' 0 - enne d - 'fptype' 0 - kappa", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__RooBernsteinEffiDictionary_774_0_10, 85, G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&RooBernsteinEffi::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__RooBernsteinEffiDictionary_774_0_11, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&RooBernsteinEffi::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__RooBernsteinEffiDictionary_774_0_12, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&RooBernsteinEffi::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__RooBernsteinEffiDictionary_774_0_13, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&RooBernsteinEffi::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__RooBernsteinEffiDictionaryLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__RooBernsteinEffiDictionary_774_0_17, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__RooBernsteinEffiDictionary_774_0_18, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&RooBernsteinEffi::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__RooBernsteinEffiDictionary_774_0_19, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&RooBernsteinEffi::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__RooBernsteinEffiDictionary_774_0_20, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&RooBernsteinEffi::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__RooBernsteinEffiDictionary_774_0_21, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&RooBernsteinEffi::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~RooBernsteinEffi", 1746, G__RooBernsteinEffiDictionary_774_0_22, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncRooBernsteinEffiDictionary() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalRooBernsteinEffiDictionary() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
}

static void G__cpp_setup_func25() {
}

static void G__cpp_setup_func26() {
}

static void G__cpp_setup_func27() {
}

static void G__cpp_setup_func28() {
}

static void G__cpp_setup_func29() {
}

static void G__cpp_setup_func30() {
}

static void G__cpp_setup_func31() {
}

static void G__cpp_setup_func32() {
}

static void G__cpp_setup_func33() {
}

static void G__cpp_setup_func34() {
}

static void G__cpp_setup_func35() {
}

static void G__cpp_setup_func36() {
}

static void G__cpp_setup_func37() {
}

static void G__cpp_setup_func38() {
}

static void G__cpp_setup_func39() {
}

static void G__cpp_setup_func40() {
}

static void G__cpp_setup_func41() {
}

static void G__cpp_setup_func42() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcRooBernsteinEffiDictionary() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
  G__cpp_setup_func25();
  G__cpp_setup_func26();
  G__cpp_setup_func27();
  G__cpp_setup_func28();
  G__cpp_setup_func29();
  G__cpp_setup_func30();
  G__cpp_setup_func31();
  G__cpp_setup_func32();
  G__cpp_setup_func33();
  G__cpp_setup_func34();
  G__cpp_setup_func35();
  G__cpp_setup_func36();
  G__cpp_setup_func37();
  G__cpp_setup_func38();
  G__cpp_setup_func39();
  G__cpp_setup_func40();
  G__cpp_setup_func41();
  G__cpp_setup_func42();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__RooBernsteinEffiDictionaryLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__RooBernsteinEffiDictionaryLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__RooBernsteinEffiDictionaryLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__RooBernsteinEffiDictionaryLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__RooBernsteinEffiDictionaryLN_TNamed = { "TNamed" , 99 , -1 };
G__linked_taginfo G__RooBernsteinEffiDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__RooBernsteinEffiDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__RooBernsteinEffiDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__RooBernsteinEffiDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__RooBernsteinEffiDictionaryLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__RooBernsteinEffiDictionaryLN_RooPrintable = { "RooPrintable" , 99 , -1 };
G__linked_taginfo G__RooBernsteinEffiDictionaryLN_listlEdoublecOallocatorlEdoublegRsPgR = { "list<double,allocator<double> >" , 99 , -1 };
G__linked_taginfo G__RooBernsteinEffiDictionaryLN_listlEstringcOallocatorlEstringgRsPgR = { "list<string,allocator<string> >" , 99 , -1 };
G__linked_taginfo G__RooBernsteinEffiDictionaryLN_RooAbsArg = { "RooAbsArg" , 99 , -1 };
G__linked_taginfo G__RooBernsteinEffiDictionaryLN_RooArgList = { "RooArgList" , 99 , -1 };
G__linked_taginfo G__RooBernsteinEffiDictionaryLN_setlEstringcOlesslEstringgRcOallocatorlEstringgRsPgR = { "set<string,less<string>,allocator<string> >" , 99 , -1 };
G__linked_taginfo G__RooBernsteinEffiDictionaryLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__RooBernsteinEffiDictionaryLN_RooListProxy = { "RooListProxy" , 99 , -1 };
G__linked_taginfo G__RooBernsteinEffiDictionaryLN_RooRealProxy = { "RooRealProxy" , 99 , -1 };
G__linked_taginfo G__RooBernsteinEffiDictionaryLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR = { "map<string,string,less<string>,allocator<pair<const string,string> > >" , 99 , -1 };
G__linked_taginfo G__RooBernsteinEffiDictionaryLN_setlEpairlERooAbsArgmUcORooAbsArgmUgRcOlesslEpairlERooAbsArgmUcORooAbsArgmUgRsPgRcOallocatorlEpairlERooAbsArgmUcORooAbsArgmUgRsPgRsPgR = { "set<pair<RooAbsArg*,RooAbsArg*>,less<pair<RooAbsArg*,RooAbsArg*> >,allocator<pair<RooAbsArg*,RooAbsArg*> > >" , 99 , -1 };
G__linked_taginfo G__RooBernsteinEffiDictionaryLN_RooAbsReal = { "RooAbsReal" , 99 , -1 };
G__linked_taginfo G__RooBernsteinEffiDictionaryLN_dequelERooAbsCachemUcOallocatorlERooAbsCachemUgRsPgR = { "deque<RooAbsCache*,allocator<RooAbsCache*> >" , 99 , -1 };
G__linked_taginfo G__RooBernsteinEffiDictionaryLN_maplERooAbsArgmUcOTRefArraymUcOlesslERooAbsArgmUgRcOallocatorlEpairlERooAbsArgmUsPconstcOTRefArraymUgRsPgRsPgR = { "map<RooAbsArg*,TRefArray*,less<RooAbsArg*>,allocator<pair<RooAbsArg* const,TRefArray*> > >" , 99 , -1 };
G__linked_taginfo G__RooBernsteinEffiDictionaryLN_dequelERooAbsArgmUcOallocatorlERooAbsArgmUgRsPgR = { "deque<RooAbsArg*,allocator<RooAbsArg*> >" , 99 , -1 };
G__linked_taginfo G__RooBernsteinEffiDictionaryLN_stacklERooAbsArgmUcOdequelERooAbsArgmUcOallocatorlERooAbsArgmUgRsPgRsPgR = { "stack<RooAbsArg*,deque<RooAbsArg*,allocator<RooAbsArg*> > >" , 99 , -1 };
G__linked_taginfo G__RooBernsteinEffiDictionaryLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__RooBernsteinEffiDictionaryLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__RooBernsteinEffiDictionaryLN_TMatrixTlEdoublegR = { "TMatrixT<double>" , 99 , -1 };
G__linked_taginfo G__RooBernsteinEffiDictionaryLN_vectorlERooCurvemUcOallocatorlERooCurvemUgRsPgR = { "vector<RooCurve*,allocator<RooCurve*> >" , 99 , -1 };
G__linked_taginfo G__RooBernsteinEffiDictionaryLN_reverse_iteratorlEvectorlERooCurvemUcOallocatorlERooCurvemUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<RooCurve*,allocator<RooCurve*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__RooBernsteinEffiDictionaryLN_maplEstringcOTH1mUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTH1mUgRsPgRsPgR = { "map<string,TH1*,less<string>,allocator<pair<const string,TH1*> > >" , 99 , -1 };
G__linked_taginfo G__RooBernsteinEffiDictionaryLN_maplEstringcORooDataHistmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcORooDataHistmUgRsPgRsPgR = { "map<string,RooDataHist*,less<string>,allocator<pair<const string,RooDataHist*> > >" , 99 , -1 };
G__linked_taginfo G__RooBernsteinEffiDictionaryLN_maplEstringcORooDataSetmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcORooDataSetmUgRsPgRsPgR = { "map<string,RooDataSet*,less<string>,allocator<pair<const string,RooDataSet*> > >" , 99 , -1 };
G__linked_taginfo G__RooBernsteinEffiDictionaryLN_maplEstringcORooAbsDatamUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcORooAbsDatamUgRsPgRsPgR = { "map<string,RooAbsData*,less<string>,allocator<pair<const string,RooAbsData*> > >" , 99 , -1 };
G__linked_taginfo G__RooBernsteinEffiDictionaryLN_listlERooAbsRealcLcLEvalErrorcOallocatorlERooAbsRealcLcLEvalErrorgRsPgR = { "list<RooAbsReal::EvalError,allocator<RooAbsReal::EvalError> >" , 99 , -1 };
G__linked_taginfo G__RooBernsteinEffiDictionaryLN_pairlEstringcOlistlERooAbsRealcLcLEvalErrorcOallocatorlERooAbsRealcLcLEvalErrorgRsPgRsPgR = { "pair<string,list<RooAbsReal::EvalError,allocator<RooAbsReal::EvalError> > >" , 115 , -1 };
G__linked_taginfo G__RooBernsteinEffiDictionaryLN_maplEconstsPRooAbsArgmUcOpairlEstringcOlistlERooAbsRealcLcLEvalErrorcOallocatorlERooAbsRealcLcLEvalErrorgRsPgRsPgRcOlesslEconstsPRooAbsArgmUgRcOallocatorlEpairlEconstsPRooAbsArgmUsPconstcOpairlEstringcOlistlERooAbsRealcLcLEvalErrorcOallocatorlERooAbsRealcLcLEvalErrorgRsPgRsPgRsPgRsPgRsPgR = { "map<const RooAbsArg*,pair<string,list<RooAbsReal::EvalError,allocator<RooAbsReal::EvalError> > >,less<const RooAbsArg*>,allocator<pair<const RooAbsArg* const,pair<string,list<RooAbsReal::EvalError,allocator<RooAbsReal::EvalError> > > > > >" , 99 , -1 };
G__linked_taginfo G__RooBernsteinEffiDictionaryLN_RooBernsteinEffi = { "RooBernsteinEffi" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableRooBernsteinEffiDictionary() {
  G__RooBernsteinEffiDictionaryLN_TClass.tagnum = -1 ;
  G__RooBernsteinEffiDictionaryLN_TBuffer.tagnum = -1 ;
  G__RooBernsteinEffiDictionaryLN_TMemberInspector.tagnum = -1 ;
  G__RooBernsteinEffiDictionaryLN_TObject.tagnum = -1 ;
  G__RooBernsteinEffiDictionaryLN_TNamed.tagnum = -1 ;
  G__RooBernsteinEffiDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__RooBernsteinEffiDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__RooBernsteinEffiDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__RooBernsteinEffiDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__RooBernsteinEffiDictionaryLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__RooBernsteinEffiDictionaryLN_RooPrintable.tagnum = -1 ;
  G__RooBernsteinEffiDictionaryLN_listlEdoublecOallocatorlEdoublegRsPgR.tagnum = -1 ;
  G__RooBernsteinEffiDictionaryLN_listlEstringcOallocatorlEstringgRsPgR.tagnum = -1 ;
  G__RooBernsteinEffiDictionaryLN_RooAbsArg.tagnum = -1 ;
  G__RooBernsteinEffiDictionaryLN_RooArgList.tagnum = -1 ;
  G__RooBernsteinEffiDictionaryLN_setlEstringcOlesslEstringgRcOallocatorlEstringgRsPgR.tagnum = -1 ;
  G__RooBernsteinEffiDictionaryLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__RooBernsteinEffiDictionaryLN_RooListProxy.tagnum = -1 ;
  G__RooBernsteinEffiDictionaryLN_RooRealProxy.tagnum = -1 ;
  G__RooBernsteinEffiDictionaryLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR.tagnum = -1 ;
  G__RooBernsteinEffiDictionaryLN_setlEpairlERooAbsArgmUcORooAbsArgmUgRcOlesslEpairlERooAbsArgmUcORooAbsArgmUgRsPgRcOallocatorlEpairlERooAbsArgmUcORooAbsArgmUgRsPgRsPgR.tagnum = -1 ;
  G__RooBernsteinEffiDictionaryLN_RooAbsReal.tagnum = -1 ;
  G__RooBernsteinEffiDictionaryLN_dequelERooAbsCachemUcOallocatorlERooAbsCachemUgRsPgR.tagnum = -1 ;
  G__RooBernsteinEffiDictionaryLN_maplERooAbsArgmUcOTRefArraymUcOlesslERooAbsArgmUgRcOallocatorlEpairlERooAbsArgmUsPconstcOTRefArraymUgRsPgRsPgR.tagnum = -1 ;
  G__RooBernsteinEffiDictionaryLN_dequelERooAbsArgmUcOallocatorlERooAbsArgmUgRsPgR.tagnum = -1 ;
  G__RooBernsteinEffiDictionaryLN_stacklERooAbsArgmUcOdequelERooAbsArgmUcOallocatorlERooAbsArgmUgRsPgRsPgR.tagnum = -1 ;
  G__RooBernsteinEffiDictionaryLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__RooBernsteinEffiDictionaryLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__RooBernsteinEffiDictionaryLN_TMatrixTlEdoublegR.tagnum = -1 ;
  G__RooBernsteinEffiDictionaryLN_vectorlERooCurvemUcOallocatorlERooCurvemUgRsPgR.tagnum = -1 ;
  G__RooBernsteinEffiDictionaryLN_reverse_iteratorlEvectorlERooCurvemUcOallocatorlERooCurvemUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__RooBernsteinEffiDictionaryLN_maplEstringcOTH1mUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTH1mUgRsPgRsPgR.tagnum = -1 ;
  G__RooBernsteinEffiDictionaryLN_maplEstringcORooDataHistmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcORooDataHistmUgRsPgRsPgR.tagnum = -1 ;
  G__RooBernsteinEffiDictionaryLN_maplEstringcORooDataSetmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcORooDataSetmUgRsPgRsPgR.tagnum = -1 ;
  G__RooBernsteinEffiDictionaryLN_maplEstringcORooAbsDatamUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcORooAbsDatamUgRsPgRsPgR.tagnum = -1 ;
  G__RooBernsteinEffiDictionaryLN_listlERooAbsRealcLcLEvalErrorcOallocatorlERooAbsRealcLcLEvalErrorgRsPgR.tagnum = -1 ;
  G__RooBernsteinEffiDictionaryLN_pairlEstringcOlistlERooAbsRealcLcLEvalErrorcOallocatorlERooAbsRealcLcLEvalErrorgRsPgRsPgR.tagnum = -1 ;
  G__RooBernsteinEffiDictionaryLN_maplEconstsPRooAbsArgmUcOpairlEstringcOlistlERooAbsRealcLcLEvalErrorcOallocatorlERooAbsRealcLcLEvalErrorgRsPgRsPgRcOlesslEconstsPRooAbsArgmUgRcOallocatorlEpairlEconstsPRooAbsArgmUsPconstcOpairlEstringcOlistlERooAbsRealcLcLEvalErrorcOallocatorlERooAbsRealcLcLEvalErrorgRsPgRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__RooBernsteinEffiDictionaryLN_RooBernsteinEffi.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableRooBernsteinEffiDictionary() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__RooBernsteinEffiDictionaryLN_TClass);
   G__get_linked_tagnum_fwd(&G__RooBernsteinEffiDictionaryLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__RooBernsteinEffiDictionaryLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__RooBernsteinEffiDictionaryLN_TObject);
   G__get_linked_tagnum_fwd(&G__RooBernsteinEffiDictionaryLN_TNamed);
   G__get_linked_tagnum_fwd(&G__RooBernsteinEffiDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__RooBernsteinEffiDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__RooBernsteinEffiDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__RooBernsteinEffiDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__RooBernsteinEffiDictionaryLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__RooBernsteinEffiDictionaryLN_RooPrintable);
   G__get_linked_tagnum_fwd(&G__RooBernsteinEffiDictionaryLN_listlEdoublecOallocatorlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__RooBernsteinEffiDictionaryLN_listlEstringcOallocatorlEstringgRsPgR);
   G__get_linked_tagnum_fwd(&G__RooBernsteinEffiDictionaryLN_RooAbsArg);
   G__get_linked_tagnum_fwd(&G__RooBernsteinEffiDictionaryLN_RooArgList);
   G__get_linked_tagnum_fwd(&G__RooBernsteinEffiDictionaryLN_setlEstringcOlesslEstringgRcOallocatorlEstringgRsPgR);
   G__get_linked_tagnum_fwd(&G__RooBernsteinEffiDictionaryLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__RooBernsteinEffiDictionaryLN_RooListProxy);
   G__get_linked_tagnum_fwd(&G__RooBernsteinEffiDictionaryLN_RooRealProxy);
   G__get_linked_tagnum_fwd(&G__RooBernsteinEffiDictionaryLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__RooBernsteinEffiDictionaryLN_setlEpairlERooAbsArgmUcORooAbsArgmUgRcOlesslEpairlERooAbsArgmUcORooAbsArgmUgRsPgRcOallocatorlEpairlERooAbsArgmUcORooAbsArgmUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__RooBernsteinEffiDictionaryLN_RooAbsReal);
   G__get_linked_tagnum_fwd(&G__RooBernsteinEffiDictionaryLN_dequelERooAbsCachemUcOallocatorlERooAbsCachemUgRsPgR);
   G__get_linked_tagnum_fwd(&G__RooBernsteinEffiDictionaryLN_maplERooAbsArgmUcOTRefArraymUcOlesslERooAbsArgmUgRcOallocatorlEpairlERooAbsArgmUsPconstcOTRefArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__RooBernsteinEffiDictionaryLN_dequelERooAbsArgmUcOallocatorlERooAbsArgmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__RooBernsteinEffiDictionaryLN_stacklERooAbsArgmUcOdequelERooAbsArgmUcOallocatorlERooAbsArgmUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__RooBernsteinEffiDictionaryLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__RooBernsteinEffiDictionaryLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__RooBernsteinEffiDictionaryLN_TMatrixTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__RooBernsteinEffiDictionaryLN_vectorlERooCurvemUcOallocatorlERooCurvemUgRsPgR);
   G__get_linked_tagnum_fwd(&G__RooBernsteinEffiDictionaryLN_reverse_iteratorlEvectorlERooCurvemUcOallocatorlERooCurvemUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__RooBernsteinEffiDictionaryLN_maplEstringcOTH1mUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTH1mUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__RooBernsteinEffiDictionaryLN_maplEstringcORooDataHistmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcORooDataHistmUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__RooBernsteinEffiDictionaryLN_maplEstringcORooDataSetmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcORooDataSetmUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__RooBernsteinEffiDictionaryLN_maplEstringcORooAbsDatamUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcORooAbsDatamUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__RooBernsteinEffiDictionaryLN_listlERooAbsRealcLcLEvalErrorcOallocatorlERooAbsRealcLcLEvalErrorgRsPgR);
   G__get_linked_tagnum_fwd(&G__RooBernsteinEffiDictionaryLN_pairlEstringcOlistlERooAbsRealcLcLEvalErrorcOallocatorlERooAbsRealcLcLEvalErrorgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__RooBernsteinEffiDictionaryLN_maplEconstsPRooAbsArgmUcOpairlEstringcOlistlERooAbsRealcLcLEvalErrorcOallocatorlERooAbsRealcLcLEvalErrorgRsPgRsPgRcOlesslEconstsPRooAbsArgmUgRcOallocatorlEpairlEconstsPRooAbsArgmUsPconstcOpairlEstringcOlistlERooAbsRealcLcLEvalErrorcOallocatorlERooAbsRealcLcLEvalErrorgRsPgRsPgRsPgRsPgRsPgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__RooBernsteinEffiDictionaryLN_RooBernsteinEffi),sizeof(RooBernsteinEffi),-1,63232,"Your description goes here...",G__setup_memvarRooBernsteinEffi,G__setup_memfuncRooBernsteinEffi);
}
extern "C" void G__cpp_setupRooBernsteinEffiDictionary(void) {
  G__check_setup_version(30051515,"G__cpp_setupRooBernsteinEffiDictionary()");
  G__set_cpp_environmentRooBernsteinEffiDictionary();
  G__cpp_setup_tagtableRooBernsteinEffiDictionary();

  G__cpp_setup_inheritanceRooBernsteinEffiDictionary();

  G__cpp_setup_typetableRooBernsteinEffiDictionary();

  G__cpp_setup_memvarRooBernsteinEffiDictionary();

  G__cpp_setup_memfuncRooBernsteinEffiDictionary();
  G__cpp_setup_globalRooBernsteinEffiDictionary();
  G__cpp_setup_funcRooBernsteinEffiDictionary();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncRooBernsteinEffiDictionary();
  return;
}
class G__cpp_setup_initRooBernsteinEffiDictionary {
  public:
    G__cpp_setup_initRooBernsteinEffiDictionary() { G__add_setup_func("RooBernsteinEffiDictionary",(G__incsetup)(&G__cpp_setupRooBernsteinEffiDictionary)); G__call_setup_funcs(); }
   ~G__cpp_setup_initRooBernsteinEffiDictionary() { G__remove_setup_func("RooBernsteinEffiDictionary"); }
};
G__cpp_setup_initRooBernsteinEffiDictionary G__cpp_setup_initializerRooBernsteinEffiDictionary;

